### ISSUE TITLE
Support to USERNOTICE for subs, and variables for sub_plan

### ISSUE THREAD

**Issue by Doc94** [Gikkman/Java-Twirk#10]
Well this library sound great...
But i need support for new system of subs, plan subs prime,1000,2000,3000.

**Comment by Gikkman** [comment]
I had not noticed that they had extended the subscribers system that much. 
Sure, I'll get around fixing that. I am currently on vacation, and won't be back till September, but I'll look at it then.

**Comment by Gikkman** [comment]
This was handled in #12
