### ISSUE TITLE
[Request] Sub USER_TYPE

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Gikkman/Java-Twirk#2]
Is there a way that you can add a sub user type?

**Comment by Gikkman** [comment]
You can check if a user is a sub, via the user.isSub() method, if you didn't know.

But I am assuming you mean to add it to the USER_TYPE enum, so you can do USER_TYPE.SUBSCRIBER? If so, sure, I can add it with the next release.

**Comment by UnRealDinnerbone** [comment]
It would be easier for commands and things

**Comment by Gikkman** [comment]
Feature added to Develop branch
