### ISSUE TITLE
CheerImpl.getImageURL does not return the correct URL

### ISSUE THREAD

**Issue by Ignamarte** [Gikkman/Java-Twirk#30]
Hey there!

`public String getImageURL(CheerTheme theme, CheerType type, CheerSize size)` from `CheerImpl.java` does not return a valid URL.  

For instance,

```scala
val cheer = new CheerImpl(100, "TEST")
val cheerType = CheerType.STATIC
val cheerTheme = CheerTheme.LIGHT
val cheerSize = CheerSize.TINY

cheer.getImageURL(cheerTheme, cheerType, cheerSize)
```

returns the following string: `static-cdn.jtvnw.net/bits/<theme>/<type>/<color>/<size>/light/static/purple/1`.

The issue, according to the method `getImageURL `, stems from the value of `ROOT_URL` which should be `static-cdn.jtvnw.net/bits` instead of `static-cdn.jtvnw.net/bits/<theme>/<type>/<color>/<size>`.

**Comment by Gikkman** [comment]
Hi!

Yes, you seem to be correct. I will fix this in an upcoming release for sure :)

Thank you for the report!

**Comment by Gikkman** [comment]
In the mean time, if you are experiencing issues, you could do a string replace on the result from the  `getImageURL`.

```
cheer.getImageURL(cheerTheme, cheerType, cheerSize).replace("/<theme>/<type>/<color>/<size>", "")
```

I think the above should work

**Comment by Ignamarte** [comment]
No problem, that's exactly what I ended up using and it works perfectly fine.

Btw, thank you for making Twirk, it has been very helpfull !
