### ISSUE TITLE
Channel Points

### ISSUE THREAD

**Issue by CreepiMatze** [Gikkman/Java-Twirk#35]
pls add a option to use Channel Points

**Comment by Gikkman** [comment]
Channel points are not visible to through the chat API, which is the only part this library covers. For a more comprehensive library, you can check out [twitch4j](https://github.com/twitch4j/twitch4j). They support the entire API, and can solve the channel point implementation.

To give some context, I aim to make it easy to make chat bots and thus I want to keep the library easy to use and understand. When I started with Twirk, my aim was to make a library that almost any person could use, even if they had just a sliver of experience with coding. Thus, I settled for covering the chat API, and leave the more complex full-api implementation to more advanced libraries.
