### ISSUE TITLE
Add `followers-only` tag to RoomState

### ISSUE THREAD

**Issue by j4ckofalltrades** [Gikkman/Java-Twirk#37]
Expose `followers-only` tag in `RoomState` - https://dev.twitch.tv/docs/irc/tags#roomstate-twitch-tags

**Comment by Gikkman** [comment]
Noted, I'll look to adding it the next time I tinker with the library!

**Comment by j4ckofalltrades** [comment]
I had a crack at adding the tag in, please have a look whenever convenient.
