### ISSUE TITLE
Chat not updating in real time

### ISSUE THREAD

**Issue by Letal1s** [Gikkman/Java-Twirk#43]
When trying to use the onAnything event, the event is only ran when previous old messages are loaded in on application start. Any messages that are sent after twirk has connected don't go through.

Whispers seem to be picked up fine when using onPrivMsg, it just doesn't pick up general chats.

This is the code I currently have:
```
static final Twirk twirk = new TwirkBuilder("XXXXXX", "XXXXXX", "oauth:XXXXXXX").setVerboseMode(true).build();

public static void main(String[] args) {
        try {
            twirk.connect();
            System.out.println("Connected to Twitch chat.");
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        twirk.addIrcListener(new TwirkListener() {
            @Override
            public void onAnything(String unformatedMessage) {
                System.out.println("Message received.");
            }
        });
}
```

I get a bunch of "Message received." logs when the application starts, but no more logs when new messages are sent in chat. I've also noticed that messages sent using twirk.channelMessage() don't show up on my page until chat is refreshed. Has something changed in Twitch recently or could it be something to do with my bot account like a setting that needs to be changed?

This happens when using the latest from the repo, not a JAR release.

Thanks.

**Comment by Gikkman** [comment]
I can't seem to reproduce it... Are you sure you get the channel right? I think it is important to have the channel name in lower-case, for some reason. Could you verify?

**Comment by Letal1s** [comment]
Aha, putting the channel name in lower case seemed to have sorted it. Sorry about that!

**Comment by Gikkman** [comment]
You do raise a good point of friction though. I'll make sure to cast the channel name to lower-case automatically in the next version!
