### ISSUE TITLE
Add the ability to join more then one channel at once 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Gikkman/Java-Twirk#5]
This would be very useful as i need a bot the needs to been in a handful of channels, thanks

**Comment by Gikkman** [comment]
I can see the benefits of this. I'm not sure how difficult it'd be to implement, but it is certainly possible.

**Comment by Gikkman** [comment]
I realised that this can currently be emulated by spawning a new instance of Twirk for each channel you want to join. Twitch allows concurrent connections it seems, so each instance can handle different channels. While it might not be the best solution in the long run, it can work should you need this feature soon. 

I have been prototyping a solution for this, but I have yet to reach a good solution. The problem I keep facing is that all Twirk method calls will need a *channel* parameter, and that becomes quite verbose IMO... Not sure if there is any other way of solving it though.

**Comment by Gikkman** [comment]
So, after pondering this design issue for a while, this is the solution I will probably go with:

Each channel will require its own Twirk-object, but they will all share the same server connection. That way, I can keep the old Twirk interface, and put the logic of joining several different channels into the TwirkBuilder. This will also get around the "every method will need a channel parameter", which I was very uncomfortable with.

Preferably, the joining of a channel will be bundled with the `TwirkBuilder.build` method. I think I'll go with `build` taking a channel parameter, which will build an instance connection to that channel in particular (method name will probably change to `buildAndJoin` ). 

Biggest issue with this is that the change is not backwards compatible.

Got any input on this idea?

**Comment by UnRealDinnerbone** [comment]
No
