### ISSUE TITLE
Provide a wiki or api to know how the system works

### ISSUE THREAD

**Issue by ALGEBRU** [Gikkman/Java-Twirk#6]
I know there is an example but I would like to see a full api discrimination each function 👍

**Comment by Gikkman** [comment]
I am not really sure I understand what you mean. There are Java docs describing each function, and the publicly available methods are all exposed on the Twirk object and the TwirkListener interface.

Come think of it, I should maybe move over to Java 8, remove the TwirkListenerBaseImp and give all interface methods in TwirkListener an empty default implementation. That way, the documentation would be visible.

My recommendation would be, check the [TwirkListener.java](https://github.com/Gikkman/Java-Twirk/blob/master/twirc/src/main/java/com/gikk/twirk/events/TwirkListener.java) interface, and if that is not enough, come back again and I'll help you further.

**Comment by ALGEBRU** [comment]
Thank you for the help. for some reason i missed the examples, sorry.
and I'll check out the files.
