### ISSUE TITLE
StreamLabs interface

### ISSUE THREAD

**Issue by ALGEBRU** [Gikkman/Java-Twirk#7]
I'm not sure how feasible this is because I don't really know how all this works but I think it would be helpful to have this library be able to interact with StreamLabs. For example detecting donations through StreamLabs.

**Comment by Gikkman** [comment]
I am totally with you that a StreamLabs library for Java would be great. However, this library is focused solely on Twitch Chat, so I won't build another service into it

With that said, I might build a StreamLabs library in the future. I would need one myself actually... In case I finish one in reasonable time, I'll let you know :-)
